#databasespring:
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIuIG4ixxYDGaD5YQmfy5MYIUSsGhg2LhFI110NTLRGcNY5TpAsnaRobf4ghztNF1lSBDPqxJtotvnzhwY11lj0CAwEAAQ==
  spring:
    datasource:
        druid:
            url: jdbc:mysql://localhost:3306/test
            username: root
            password: e4AkIav7JKsXHEWj87r3I7Wqio76CMxPENw4l6JB4yWvBacTSnL9w7oihMpobXWeVhgnelBOgiokQt6ZnXfbWg==
            driver-class-name: com.mysql.jdbc.Driver
            #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
            initial-size: 5
            #最小连接池数量
            min-idle: 5
            #最大连接池数量
            max-active: 20
            #获取连接时最大等待时间，单位毫秒。
            #配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
            max-wait: 60000
            #有两个含义：
            # 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
            # 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
            time-between-eviction-runs-millis: 60000
            #	连接保持空闲而不被驱逐的最小时间
            min-evictable-idle-time-millis: 120000
            max-evictable-idle-time-millis: 300000
            #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
            #如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
            validation-query: select 'x'
            #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            test-while-idle: true
            #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            test-on-borrow: false
            #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            test-on-return: false
            #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
            pool-prepared-statements: false
            connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
            #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
            #在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
            #max-pool-prepared-statement-per-connection-size: 20
            filter:
              # 开启 StatFilter，默认开启，可通过 'enabled: false' 关闭
              stat:
                 enabled: true
                 log-slow-sql: true
                 slow-sql-millis: 1000
              # 开启 Slf4jFilter
              slf4j:
                  enabled: true
                  data-source-log-enabled: false
                  connection-log-enabled: false
                  statement-log-enabled: false
                  result-set-log-enabled: false
              # 开启 WallFilter
              wall:
                  enabled: true
                  log-violation: true
                  throw-exception: false
                  ## WallConfig 配置
                  config:
                      delete-where-none-check: true
              # 开启 ConfigFilter
              config:
                  enabled: true
            stat-view-servlet:
              enabled: true
              login-username: druid
              login-password: druid
            web-stat-filter:
              enabled: true
              exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#    security:
#      user:
#        name: user
#        password: user

  server:
    port: 8080


  logging:
    level:
      root: info


  mybatis:
      table:
          auto: update
      model:
          pack: com.staging.frame.web.model
      database:
          type: mysql
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.staging.frame.web.model.*
      
